from hashlib import sha256

from excalibur_server.src.bip39.words import WORDS


def to_mnemonic(ent: bytes) -> list[str]:
    """
    Converts an array of bytes into a mnemonic sentence.

    Adapted from the [BIP39 process](https://github.com/bitcoin/bips/blob/c9a6ca6/bip-0039.mediawiki).

    :param ent: Bytes to convert into a mnemonic sentence
    :returns: Words representing the mnemonic sentence
    :raises ValueError: If the input length is invalid
    """

    if len(ent) < 16 or len(ent) > 32 or len(ent) % 4 != 0:
        raise ValueError(f"Invalid length {len(ent)}; must be between 16 and 32 bytes and multiple of 4")

    # "A checksum is generated by taking the first ENT / 32 bits of its SHA256 hash"
    digest = sha256(ent).digest()
    numChecksumBits = len(ent) / 4

    # Combine input array and checksum byte into one buffer
    # (We only need the first byte of the digest since max checksum length is 8 bits)
    combined = bytes(ent + digest[:1])
    totalBits = len(ent) * 8 + numChecksumBits
    numWords = totalBits / 11

    # Process the combined buffer as a bitstream to extract 11-bit indices
    indices = []
    accumulator = 0
    bits = 0
    bufferIndex = 0
    while len(indices) < numWords:
        while bits < 11:
            accumulator = (accumulator << 8) | combined[bufferIndex]
            bufferIndex += 1
            bits += 8

        shift = bits - 11  # Bits to shift to isolate top 11 bits
        wordIndex = accumulator >> shift
        indices.append(wordIndex)

        # Remove the extracted 11 bits from the accumulator
        bits -= 11
        mask = (1 << bits) - 1  # Create a mask for the remaining bits
        accumulator &= mask

    # "[W]e convert these numbers into words and use the joined words as a mnemonic sentence"
    mnemonic = [WORDS[index] for index in indices]
    return mnemonic


def from_mnemonic(mnemonic: list[str]) -> bytes:
    """
    Converts a mnemonic sentence as generated by `to_mnemonic()` back into an array of bytes

    :param mnemonic: Words representing the mnemonic sentence
    :returns: Bytes representing the mnemonic sentence
    :raises ValueError: If the input length is invalid
    :raises ValueError: If a word is not found in the word list
    :raises ValueError: If the checksum does not match
    """

    if len(mnemonic) < 12 or len(mnemonic) > 24 or len(mnemonic) % 3 != 0:
        raise ValueError(f"Invalid length {len(mnemonic)}; must be between 12 and 24 words and multiple of 3")

    # Convert words to their 11-bit indices and concatenate into a bit string
    bits = "".join([bin(WORDS.index(word))[2:].zfill(11) for word in mnemonic])

    # Split the bits into entropy and checksum
    numChecksumBits = len(mnemonic) // 3
    entropyBits = bits[: len(bits) - numChecksumBits]
    checksumBits = bits[len(bits) - numChecksumBits :]

    # Convert the entropy bits back into a byte array
    entropy = bytes(int(entropyBits[i : i + 8], 2) for i in range(0, len(entropyBits), 8))

    # Validate checksum
    digest = sha256(entropy).digest()
    expectedChecksumBits = bin(digest[0])[2:].zfill(8)[:numChecksumBits]
    if expectedChecksumBits != checksumBits:
        raise ValueError("Invalid checksum")

    return entropy
