packages:
  - app
  - app/packages/**

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - core-js
  - cypress
  - electron
  - electron-winstaller
  - esbuild
  - sharp

overrides:
  glob: ^11.1.0
  qs@<6.14.1: ^6.14.1

sideEffectsCache: false

virtualStoreDirMaxLength: 60
