packages:
  - website

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - core-js-pure
  - sharp

sideEffectsCache: false
virtualStoreDirMaxLength: 60 # Make this a common setting between different operating systems
