packages:
  - website

minimumReleaseAge: 7200 # 5 days, expressed in minutes
minimumReleaseAgeExclude:
  - uuid@14.0.0

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - core-js-pure
  - sharp

overrides:
  serialize-javascript@<7.0.5: ">=7.0.5"
  uuid@<14.0.0: ">=14.0.0"

sideEffectsCache: false

virtualStoreDirMaxLength: 60 # Make this a common setting between different operating systems
