import fs from "fs";
import path from "path";
import { PluginOption } from "vite";

const COLOURS_CSS = "colours.css";
const COLOURS_GEN_CSS = "colours.gen.css";
const THEME_REFERENCE_CSS = "_theme_reference.css";

/**
 * Converts OKLCH color values to sRGB.
 */
function oklchToRGB(l: number, c: number, h: number): { r: number; g: number; b: number } {
    // Convert OKLCH to OKLAB
    const hRad = (h * Math.PI) / 180;
    const a = c * Math.cos(hRad);
    const b = c * Math.sin(hRad);

    // Convert OKLAB to LMS
    const l_ = l + 0.3963377774 * a + 0.2158037573 * b;
    const m_ = l - 0.1055613458 * a - 0.0638541728 * b;
    const s_ = l - 0.0894841775 * a - 1.291485548 * b;

    const l_cube = l_ * l_ * l_;
    const m_cube = m_ * m_ * m_;
    const s_cube = s_ * s_ * s_;

    // LMS to Linear sRGB
    const rLin = +4.0767416621 * l_cube - 3.3077115913 * m_cube + 0.2309699292 * s_cube;
    const gLin = -1.2684380046 * l_cube + 2.6097574011 * m_cube - 0.3413193965 * s_cube;
    const bLin = -0.0041960863 * l_cube - 0.7034186147 * m_cube + 1.707614701 * s_cube;

    // Linear sRGB to sRGB
    const toSRGB = (val: number) => {
        const clamped = Math.max(0, Math.min(1, val)); // Clamp to 0-1 to handle out-of-gamut
        return clamped <= 0.0031308 ? 12.92 * clamped : 1.055 * Math.pow(clamped, 1 / 2.4) - 0.055;
    };

    return {
        r: Math.round(toSRGB(rLin) * 255),
        g: Math.round(toSRGB(gLin) * 255),
        b: Math.round(toSRGB(bLin) * 255),
    };
}

/**
 * Generates the Ionic theme CSS file from the Tailwind theme reference and colour map.
 */
function generateTheme() {
    // Load files
    const coloursCss = fs.readFileSync(path.resolve(__dirname, COLOURS_CSS), "utf-8");
    const themeReferenceCss = fs.readFileSync(path.resolve(__dirname, THEME_REFERENCE_CSS), "utf-8");

    // Get the Tailwind color values (e.g., "oklch(62.3% 0.214 259.815)")
    const themeReferenceMap: Record<string, { l: number; c: number; h: number }> = {};
    const themeReferenceRegex = /(?<var>--.+):\s?oklch\((?<l>\d*\.?\d+)%\s+(?<c>\d*\.?\d+)\s+(?<h>\d*\.?\d+)\);?\n/gm;
    const themeReferenceMatches = themeReferenceCss.matchAll(themeReferenceRegex);
    for (const match of themeReferenceMatches) {
        themeReferenceMap[match.groups!.var] = {
            l: parseFloat(match.groups!.l) / 100, // Original element is a percentage, convert to 0-1
            c: parseFloat(match.groups!.c),
            h: parseFloat(match.groups!.h),
        };
    }

    // Generate lines for the CSS file
    const colourMapRegex = /(?<ion_var>--.+):\s?var\((?<tailwind_var>--.+)\);?/m;

    const origLines = coloursCss.split("\n");
    const newLines: string[] = [];

    for (const line of origLines) {
        newLines.push(line);
        const match = line.match(colourMapRegex);
        if (!match) {
            // No colour specified in that line; can continue
            continue;
        }

        // Convert Tailwind colour to RGB
        const ionVar = match.groups!.ion_var;
        const tailwindVar = match.groups!.tailwind_var;

        const tailwindColour = themeReferenceMap[tailwindVar];
        const rgb = oklchToRGB(tailwindColour.l, tailwindColour.c, tailwindColour.h);
        newLines.push(`    ${ionVar}-rgb: ${rgb.r}, ${rgb.g}, ${rgb.b};`);
    }

    // Write file
    const cssContent = `/**\n * Auto-generated by sync-theme.ts. DO NOT MODIFY!\n */\n\n${newLines.join("\n")}\n`;
    fs.writeFileSync(path.join(__dirname, COLOURS_GEN_CSS), cssContent);
}

/**
 * Vite plugin that generates the Ionic theme CSS file.
 */
export function syncTheme(): PluginOption {
    return {
        name: "ionic-tailwind-sync-theme",
        buildStart() {
            generateTheme();
        },
        handleHotUpdate({ file }) {
            // Rebuild on hot reload
            if (file.endsWith(COLOURS_CSS) || file.endsWith(THEME_REFERENCE_CSS)) {
                generateTheme();
            }
        },
    };
}
