import { oklch2rgb } from "colorizr";
import fs from "fs";
import path from "path";
import { PluginOption } from "vite";

const COLOURS_CSS = "colours.css";
const COLOURS_GEN_CSS = "colours.gen.css";
const THEME_REFERENCE_CSS = "_theme_reference.css";

/**
 * Generates the Ionic theme CSS file from the Tailwind theme reference and colour map.
 */
function generateTheme() {
    // Load files
    const coloursCss = fs.readFileSync(path.resolve(__dirname, COLOURS_CSS), "utf-8");
    const themeReferenceCss = fs.readFileSync(path.resolve(__dirname, THEME_REFERENCE_CSS), "utf-8");

    // Get the Tailwind color values (e.g., "oklch(62.3% 0.214 259.815)")
    const themeReferenceMap: Record<string, { l: number; c: number; h: number }> = {};
    const themeReferenceRegex = /(?<var>--.+):\s?oklch\((?<l>\d*\.?\d+)%\s+(?<c>\d*\.?\d+)\s+(?<h>\d*\.?\d+)\);?\n/gm;
    const themeReferenceMatches = themeReferenceCss.matchAll(themeReferenceRegex);
    for (const match of themeReferenceMatches) {
        themeReferenceMap[match.groups!.var] = {
            l: parseFloat(match.groups!.l) / 100, // Original element is a percentage, convert to 0-1
            c: parseFloat(match.groups!.c),
            h: parseFloat(match.groups!.h),
        };
    }

    // Generate lines for the CSS file
    const colourMapRegex = /(?<ion_var>--.+):\s?var\((?<tailwind_var>--.+)\);?/m;

    const origLines = coloursCss.split("\n");
    const newLines: string[] = [];

    for (const line of origLines) {
        newLines.push(line);
        const match = line.match(colourMapRegex);
        if (!match) {
            // No colour specified in that line; can continue
            continue;
        }

        // Convert Tailwind colour to RGB
        const ionVar = match.groups!.ion_var;
        const tailwindVar = match.groups!.tailwind_var;

        const tailwindColour = themeReferenceMap[tailwindVar];
        const rgb = oklch2rgb({ l: tailwindColour.l, c: tailwindColour.c, h: tailwindColour.h });
        newLines.push(`    ${ionVar}-rgb: ${rgb.r}, ${rgb.g}, ${rgb.b};`);
    }

    // Write file
    const cssContent = `/* Auto-generated by sync-theme.ts */\n${newLines.join("\n")}\n`;
    fs.writeFileSync(path.join(__dirname, COLOURS_GEN_CSS), cssContent);
}

/**
 * Vite plugin that generates the Ionic theme CSS file.
 */
export function syncTheme(): PluginOption {
    return {
        name: "ionic-tailwind-sync-theme",
        buildStart() {
            generateTheme();
        },
        handleHotUpdate({ file }) {
            // Rebuild on hot reload
            if (file.endsWith(COLOURS_CSS) || file.endsWith(THEME_REFERENCE_CSS)) {
                generateTheme();
            }
        },
    };
}
