[build-system]
requires = ["uv_build>=0.10.9,<0.11.0"]
build-backend = "uv_build"

[project]
name = "excalibur-server"
version = "0.6.0a4"
dependencies = [
    "aiofiles>=25.1.0",
    "alembic>=1.18.4",
    "duckdb~=1.4.4",
    "duckdb-engine>=0.17.0",
    "fastapi>=0.135.2",
    "gitpython>=3.1.46",
    "packaging>=25.0",
    "pycryptodome>=3.23.0",
    "pydantic>=2.12.5",
    "pydantic-settings>=2.13.1",
    "pyjwt>=2.12.1",
    "rapidfuzz>=3.14.3",
    "semver>=3.0.4",
    "sqlalchemy<=2.0.44",        # Seems to be an issue with `alembic`, `duckdb`, and `sqlalchemy` versions > 2.0.44
    "sqlmodel>=0.0.37",
    "toml>=0.10.2",
    "tomlkit>=0.14.0",
    "typer>=0.24.1",
    "uvicorn[standard]>=0.41.0",
    "watchdog>=6.0.0",
    "websockets>=16.0",
]
requires-python = ">=3.11"
authors = [
    { name = "PhotonicGluon", "email" = "25820201+PhotonicGluon@users.noreply.github.com" },
]
description = "A trustless, secure file management solution using military-grade encryption"
readme = "README.md"
license = "GPL-3.0-or-later"

[project.urls]
Repository = "https://github.com/PhotonicGluon/Excalibur.git"
Issues = "https://github.com/PhotonicGluon/Excalibur/issues"

[project.scripts]
excalibur = "excalibur_server.cli:app"

[dependency-groups]
dev = ["ipython~=9.10.1", "pytest-timeout>=2.4.0", "ruff>=0.15.8"]
test = ["httpx>=0.28.1", "pytest>=9.0.2"]

[tool.uv]
default-groups = []

[tool.uv.build-backend]
module-name = "excalibur_server"
module-root = ""
source-exclude = [
    "test*",                             # All test files are excluded
    "excalibur_server/conftest.py",      # Conftest is excluded
    "excalibur_server/cli/build.py",     # Build command is excluded
    "excalibur_server/cli/run_tests.py", # Testing command is excluded
]

[tool.uv.workspace]
members = ["dist/excalibur-server-test"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "E501", # line-too-long
    "C901", # too-complex
    "I001", # unsorted-imports
    "I002", # missing-required-import
]
