[build-system]
requires = ["uv_build>=0.11.26,<0.12.0"]
build-backend = "uv_build"

[project]
name = "excalibur-server"
version = "0.8.0a4"
dependencies = [
    "aiofiles>=25.1.0",
    "alembic>=1.18.5",
    "duckdb~=1.5.5",
    "duckdb-engine>=0.17.0",
    "fastapi>=0.139.2",
    "gitpython>=3.1.57",
    "httptools>=0.8.0",
    "packaging>=26.2",
    "pycryptodome>=3.23.0",
    "pydantic>=2.13.4",
    "pydantic-settings>=2.14.2",
    "pyjwt>=2.13.0",
    "rapidfuzz>=3.14.5",
    "semver>=3.0.4",
    # Seems to be an issue with `alembic`, `duckdb`, and `sqlalchemy` versions > 2.0.44
    "sqlalchemy<=2.0.44",
    "sqlmodel>=0.0.39",
    "toml>=0.10.2",
    "tomlkit>=0.15.1",
    "typer>=0.27.0",
    "uvicorn>=0.52.0",
    "uvloop>=0.22.1 ; platform_python_implementation != 'PyPy' and sys_platform != 'cygwin' and sys_platform != 'win32'",
    "websockets>=17.0",
]
requires-python = ">=3.11"
authors = [
    { name = "PhotonicGluon", "email" = "25820201+PhotonicGluon@users.noreply.github.com" },
]
description = "A trustless, secure file management solution using zero-trust security and enterprise-grade encryption"
readme = "README.md"
license = "GPL-3.0-or-later"

[project.urls]
Repository = "https://github.com/PhotonicGluon/Excalibur.git"
Issues = "https://github.com/PhotonicGluon/Excalibur/issues"

[project.scripts]
excalibur = "excalibur_server.cli:app"

[dependency-groups]
dev = ["ipython~=9.15.0", "ruff>=0.16.0", "watchfiles>=1.2.0"]
test = ["httpx2>=2.9.1", "pytest>=9.1.1", "pytest-timeout>=2.4.0"]

[tool.uv]
default-groups = []
exclude-newer = "5 days"

[tool.uv.exclude-newer-package]
starlette = "2026-06-17T00:00:00.000Z"

[tool.uv.build-backend]
module-name = "excalibur_server"
module-root = ""
source-exclude = [
    "test*",                             # All test files are excluded
    "excalibur_server/conftest.py",      # Conftest is excluded
    "excalibur_server/cli/build.py",     # Build command is excluded
    "excalibur_server/cli/run_tests.py", # Testing command is excluded
]

[tool.uv.workspace]
members = ["dist/excalibur-server-test"]

[tool.ruff]
line-length = 120

[tool.ruff.lint]
extend-select = [
    "E401", # multiple-imports-on-one-line 
    "E402", # module-import-not-at-top-of-file
    "E501", # line-too-long
    "E701", # multiple-statements-on-one-line-colon
    "E702", # multiple-statements-on-one-line-semicolon
    "E703", # useless-semicolon
    "E711", # none-comparison
    "E712", # true-false-comparison
    "E713", # not-in-test
    "E714", # not-is-test
    "E721", # type-comparison
    "E731", # lambda-assignment
    "E741", # ambiguous-variable-name
    "E742", # ambiguous-class-name
    "E743", # ambiguous-function-name
    "F403", # undefined-local-with-import-star
    "F405", # undefined-local-with-import-star-usage
    "F406", # undefined-local-with-nested-import-star-usage
    "C901", # too-complex
    "I002", # missing-required-import
]
ignore = [
    "B008", # function-call-in-default-argument
]
