[tool.poetry]
name = "excalibur-server"
version = "0.0.1"
description = "An encrypted file server."
authors = ["The-Photons"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"

aiofiles = "^24.1.0"
cachetools = "^5.5.2"
fastapi = "^0.115.14"
pycryptodome = "^3.23.0"
pydantic = "^2.11.7"
pyjwt = "^2.10.1"
python-multipart = "^0.0.20"
typer = "^0.15.4"
uvicorn = { extras = ["standard"], version = "^0.34.3" }

[tool.poetry.group.test.dependencies]
httpx = "^0.28.1"
pytest = "^8.4.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
excalibur = "excalibur_server.cli:app"
