import { createHash } from "crypto";

import { WORDLIST, WORD_MAP } from "./wordlist";

/**
 * Converts an array of bytes into a mnemonic sentence
 *
 * Adapted from the [BIP39 process](https://github.com/bitcoin/bips/blob/c9a6ca6/bip-0039.mediawiki).
 *
 * @param ent Bytes to convert into a mnemonic sentence
 * @returns Words representing the mnemonic sentence
 * @throws {Error} If the input length is invalid
 */
function toMnemonic(ent: Buffer): string[] {
    if (ent.length < 16 || ent.length > 32 || ent.length % 4 !== 0) {
        throw new Error("Invalid length; must be between 16 and 32 bytes and multiple of 4");
    }

    // "A checksum is generated by taking the first ENT / 32 bits of its SHA256 hash"
    const digest = createHash("sha256").update(ent).digest();
    const numChecksumBits = ent.length / 4;

    // Combine input array and checksum byte into one buffer
    // (We only need the first byte of the digest since max checksum length is 8 bits)
    const combined = Buffer.concat([Buffer.from(ent), digest.subarray(0, 1)]);
    const totalBits = ent.length * 8 + numChecksumBits;
    const numWords = totalBits / 11;

    // Process the combined buffer as a bitstream to extract 11-bit indices
    const indices: number[] = [];
    let accumulator = 0;
    let bits = 0;
    let bufferIndex = 0;
    while (indices.length < numWords) {
        while (bits < 11) {
            accumulator = (accumulator << 8) | combined[bufferIndex++];
            bits += 8;
        }

        const shift = bits - 11; // Bits to shift to isolate top 11 bits
        const wordIndex = accumulator >> shift;
        indices.push(wordIndex);

        // Remove the extracted 11 bits from the accumulator
        bits -= 11;
        const mask = (1 << bits) - 1; // Create a mask for the remaining bits
        accumulator &= mask;
    }

    // "[W]e convert these numbers into words and use the joined words as a mnemonic sentence"
    const mnemonic = indices.map((index) => WORDLIST[index]);
    return mnemonic;
}

/**
 * Converts a mnemonic sentence as generated by {@link toMnemonic} back into an array of bytes
 *
 * @param mnemonic Words representing the mnemonic sentence
 * @returns Bytes representing the mnemonic sentence
 * @throws {Error} If the input length is invalid
 * @throws {Error} If a word is not found in the word list
 * @throws {Error} If the checksum does not match
 */
function fromMnemonic(mnemonic: string[]): Buffer {
    if (mnemonic.length < 12 || mnemonic.length > 24 || mnemonic.length % 3 !== 0) {
        throw new Error("Invalid length");
    }

    // Convert words to their 11-bit indices and concatenate into a bit string
    const bits = mnemonic
        .map((word) => {
            const index = WORD_MAP[word];
            if (index === undefined) {
                throw new Error(`Invalid mnemonic word: ${word}`);
            }
            return index.toString(2).padStart(11, "0");
        })
        .join("");

    // Split the bits into entropy and checksum
    const numChecksumBits = mnemonic.length / 3;
    const entropyBits = bits.slice(0, bits.length - numChecksumBits);
    const checksumBits = bits.slice(bits.length - numChecksumBits);

    // Convert the entropy bits back into a byte array
    const entropy = Buffer.from(entropyBits.match(/.{1,8}/g)!.map((byte) => parseInt(byte, 2)));

    // Validate checksum
    const digest = createHash("sha256").update(entropy).digest();
    const expectedChecksumBits = digest[0].toString(2).padStart(8, "0").slice(0, numChecksumBits);

    if (expectedChecksumBits !== checksumBits) {
        throw new Error("Invalid checksum");
    }

    return entropy;
}

export { fromMnemonic, toMnemonic };
