"""
Create FSNameable table

Revision ID: 438cddc6f4c8
Revises: 24ec4622b630
Create Date: 2025-08-30 17:01:03.794390
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# Revision identifiers used by Alembic
revision: str = "438cddc6f4c8"
down_revision: Union[str, Sequence[str], None] = "24ec4622b630"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fsnameable",
        sa.Column("uuid", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("uuid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fsnameable")
    # ### end Alembic commands ###
