"""
Add SRP group to User

Revision ID: 24ec4622b630
Revises: d5f6ecc5fa23
Create Date: 2025-08-15 15:14:40.738532
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision identifiers used by Alembic
revision: str = "24ec4622b630"
down_revision: Union[str, Sequence[str], None] = "d5f6ecc5fa23"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

srpgroup = sa.Enum("SMALL", "MEDIUM", "LARGE", name="srpgroup")


def upgrade() -> None:
    """
    Upgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    srpgroup.create(op.get_bind())
    op.add_column("user", sa.Column("srp_group", srpgroup, server_default="SMALL"))
    op.alter_column("user", "srp_group", existing_type=srpgroup, nullable=False)
    op.alter_column("user", "verifier", new_column_name="srp_verifier")
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "srp_verifier", new_column_name="verifier")
    op.drop_column("user", "srp_group")
    srpgroup.drop(op.get_bind())
    # ### end Alembic commands ###
