"""
Update User table

Revision ID: d5f6ecc5fa23
Revises: 6751bb101c16
Create Date: 2025-08-15 14:44:19.197331
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Revision identifiers used by Alembic
revision: str = "d5f6ecc5fa23"
down_revision: Union[str, Sequence[str], None] = "6751bb101c16"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "auk_salt", existing_type=sa.LargeBinary(), type_=sa.LargeBinary(length=32), nullable=False)
    op.alter_column("user", "srp_salt", existing_type=sa.LargeBinary(), type_=sa.LargeBinary(length=32), nullable=False)
    op.alter_column("user", "key_enc", existing_type=sa.LargeBinary(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """

    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "auk_salt", existing_type=sa.LargeBinary(length=32), type_=sa.LargeBinary(), nullable=False)
    op.alter_column("user", "srp_salt", existing_type=sa.LargeBinary(length=32), type_=sa.LargeBinary(), nullable=False)
    op.alter_column("user", "key_enc", existing_type=sa.LargeBinary(), nullable=True)
    # ### end Alembic commands ###
