"""
Create User table

Revision ID: 6751bb101c16
Revises: 
Create Date: 2025-08-08 19:27:02.852488
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# Revision identifiers used by Alembic
revision: str = '6751bb101c16'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('auk_salt', sa.LargeBinary(), nullable=False),
    sa.Column('srp_salt', sa.LargeBinary(), nullable=False),
    sa.Column('verifier', sa.LargeBinary(), nullable=False),
    sa.Column('key_enc', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
