"""
Add skeleton of User table

Revision ID: 97acf8c4b885
Revises: 
Create Date: 2025-08-07 17:20:33.604160
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Revision identifiers used by Alembic
revision: str = '97acf8c4b885'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """
    Upgrade schema.
    """
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('uuid', name=op.f('pk_User')),
    sa.UniqueConstraint('username', name=op.f('uq_User_username'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """
    Downgrade schema.
    """
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
