import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
    docs: [
        "welcome",
        {
            type: "category",
            label: "Quickstart",
            link: {
                type: "generated-index",
                description: "Get started with Excalibur by following these guides!",
                keywords: ["quickstart"],
            },
            items: [{ type: "autogenerated", dirName: "quickstart" }],
        },
        {
            type: "category",
            label: "Custom Client",
            link: {
                type: "generated-index",
                description:
                    "Want to make your own client to communicate with an Excalibur server? Follow these guides!",
                keywords: ["custom-client"],
            },
            items: [{ type: "autogenerated", dirName: "custom-client" }],
        },
    ],
    api: [{ type: "autogenerated", dirName: "api" }],
};

export default sidebars;
