import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
    guide: [
        "guide/welcome",
        {
            type: "category",
            label: "Quickstart",
            link: {
                type: "generated-index",
                description: "Get started with Excalibur by following these guides!",
                keywords: ["quickstart"],
            },
            items: [{ type: "autogenerated", dirName: "guide/quickstart" }],
        },
        "guide/interface",
        "guide/attestations",
        {
            type: "category",
            label: "Upgrade Guides",
            link: {
                type: "generated-index",
                description: "Upgrade guides between Excalibur versions.",
                keywords: ["upgrade-guide"],
            },
            items: [{ type: "autogenerated", dirName: "guide/upgrading" }],
        },
    ],
    reference: [
        "reference/architecture",
        "reference/security-model",
        "reference/keygen",
        "reference/name-obfuscation",
        "reference/exef",
    ],
    server_api: [
        "server-api/logging-in",
        {
            type: "category",
            label: "Authentication",
            link: {
                type: "generated-index",
                title: "Authentication",
                description:
                    "Although some of the endpoints of the server is available without authentication, any client who wishes to access their files need to authenticate themselves with the server. Excalibur uses an Augmented Password Authenticated Key Exchange (aPAKE) protocol combined with Proof-of-Possession (PoP) to ensure secure authentication.",
            },
            items: ["server-api/authentication/opaque", "server-api/authentication/subsequent"],
        },
        "server-api/encrypted-requests-and-responses",
        "server-api/files",
        "server-api/additional-user-info",
    ],
};

export default sidebars;
