import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

const sidebars: SidebarsConfig = {
    guide: [
        "guide/welcome",
        {
            type: "category",
            label: "Quickstart",
            link: {
                type: "generated-index",
                description: "Get started with Excalibur by following these guides!",
                keywords: ["quickstart"],
            },
            items: [{ type: "autogenerated", dirName: "guide/quickstart" }],
        },
        "guide/interface",
        "guide/attestations",
        {
            type: "category",
            label: "Upgrade Guides",
            link: {
                type: "generated-index",
                description: "Upgrade guides between Excalibur versions.",
                keywords: ["upgrade-guide"],
            },
            items: [{ type: "autogenerated", dirName: "guide/upgrading" }],
        },
    ],
    reference: [{ type: "autogenerated", dirName: "reference" }],
};

export default sidebars;
