name: Release Builds

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  build-server:
    name: Build Server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "./server/pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v6.5.0
        with:
          enable-cache: true
          version: "0.8.17"

      - name: Build Server
        working-directory: ./server
        run: |
          uv run --no-dev excalibur build

      - name: Upload Server Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: server
          path: server/dist
          if-no-files-found: error

  build-pwa:
    name: Build PWA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: "22"
          cache: "npm"

      - name: Install Dependencies
        working-directory: ./app
        run: npm ci

      - name: Build PWA
        working-directory: ./app
        run: |
          npm run build

      - name: Upload PWA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-pwa
          path: app/dist/
          if-no-files-found: error

  # TODO: Fix
  # build-android:
  #   name: Build Android App
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v5

  #     - name: Set up JDK 17
  #       uses: actions/setup-java@v5
  #       with:
  #         java-version: "17"
  #         distribution: "temurin"

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: "20"
  #         cache: "npm"

  #     - name: Install Android SDK
  #       uses: android-actions/setup-android@v2

  #     - name: Build Android App
  #       working-directory: ./app
  #       run: |
  #         npm ci
  #         npx cap sync android
  #         cd android
  #         ./gradlew assembleRelease

  #     - name: Upload APK
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: android-app
  #         path: app/android/app/build/outputs/apk/release/*.apk
  #         if-no-files-found: error
