name: Release Builds

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+*"
    workflow_dispatch:

jobs:
    build-app-electron:
        name: Build App (Electron)
        if: ${{ !github.event.act_skip_electron_builds }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        permissions:
            id-token: write
            contents: read
            attestations: write

        steps:
            - uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "pnpm"
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install Dependencies
              working-directory: ./app/packages/electron
              run: pnpm install

            - name: Build Windows
              if: matrix.os == 'windows-latest'
              working-directory: ./app/packages/electron
              run: |
                  pnpm run build:win

            - name: Build macOS
              if: matrix.os == 'macos-latest'
              working-directory: ./app/packages/electron
              run: |
                  pnpm run build:mac

            - name: Build Linux
              if: matrix.os == 'ubuntu-latest'
              working-directory: ./app/packages/electron
              run: |
                  pnpm run build:linux

            - name: Attest
              uses: actions/attest-build-provenance@v3
              if: ${{ !env.ACT && !github.event.repository.private }}
              with:
                  subject-path: "app/packages/electron/dist"

            - name: Upload Electron Artifacts
              uses: actions/upload-artifact@v5
              with:
                  name: app-electron-${{ matrix.os }}
                  path: |
                      app/packages/electron/dist/*.exe
                      app/packages/electron/dist/*.zip
                      app/packages/electron/dist/*.dmg
                      app/packages/electron/dist/*.AppImage
                      app/packages/electron/dist/*.snap
                      app/packages/electron/dist/*.deb
                      app/packages/electron/dist/*.rpm
                      app/packages/electron/dist/*.tar.gz
                  if-no-files-found: error

    build-app-pwa-mobile:
        name: Build App (PWA & Mobile)
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            attestations: write
        steps:
            - uses: actions/checkout@v5

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "pnpm"
                  cache-dependency-path: pnpm-lock.yaml

            - name: Set up JDK
              uses: actions/setup-java@v5
              with:
                  java-version: "21"
                  distribution: "temurin"
                  cache: "gradle"

            - name: Set up Android SDK
              uses: android-actions/setup-android@v3

            - name: Install Dependencies
              working-directory: ./app
              run: pnpm install --filter !excalibur-electron

            - name: Build PWA
              working-directory: ./app/packages/main
              run: |
                  pnpm run build
                  zip -r app-${{ github.ref_name }}-pwa.zip ./dist

            - name: Attest
              uses: actions/attest-build-provenance@v3
              if: ${{ !env.ACT && !github.event.repository.private }}
              with:
                  subject-path: "app/packages/main/app-${{ github.ref_name }}-pwa.zip"

            - name: Upload PWA Artifact
              uses: actions/upload-artifact@v5
              with:
                  name: app-pwa
                  path: app/packages/main/app-${{ github.ref_name }}-pwa.zip
                  if-no-files-found: error

            - name: Sync Capacitor
              working-directory: ./app/packages/main
              run: pnpm run sync

            - name: Grant execute permission for gradlew
              working-directory: ./app/packages/android
              run: chmod +x gradlew

            - name: Build with Gradle
              working-directory: ./app/packages/android
              run: ./gradlew --console plain build

            - name: Build Unsigned Release APK
              working-directory: ./app/packages/android
              run: ./gradlew --console plain assembleRelease

            - name: Sign app APK
              uses: ilharp/sign-android-release@v2
              with:
                  releaseDir: ./app/packages/android/app/build/outputs/apk/release
                  signingKey: ${{ secrets.ANDROID_SIGNING_KEY_BASE64 }}
                  keyAlias: ${{ secrets.ANDROID_SIGNING_KEY_ALIAS }}
                  keyStorePassword: ${{ secrets.ANDROID_SIGNING_KEY_STORE_PASSWORD }}
                  keyPassword: ${{ secrets.ANDROID_SIGNING_KEY_PASSWORD }}
                  buildToolsVersion: 36.0.0

            - name: Rename Release APK
              working-directory: ./app/packages/android/app/build/outputs/apk/release
              run: |
                  for f in *-signed.apk; do
                    mv -- "$f" ./app-${{ github.ref_name }}-release.apk
                  done

            - name: Attest
              uses: actions/attest-build-provenance@v3
              if: ${{ !env.ACT && !github.event.repository.private }}
              with:
                  subject-path: "app/packages/android/app/build/outputs/apk/release/app-${{ github.ref_name }}-release.apk"

            - name: Upload Release APK
              uses: actions/upload-artifact@v5
              with:
                  name: app-android
                  path: app/packages/android/app/build/outputs/apk/release/app-${{ github.ref_name }}-release.apk
                  if-no-files-found: error

    build-server:
        name: Build Server
        runs-on: ubuntu-latest
        permissions:
            id-token: write
            contents: read
            attestations: write
        steps:
            - uses: actions/checkout@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: "./server/pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@v7.1.0
              with:
                  enable-cache: true
                  version: "0.9.3"
                  cache-dependency-glob: "server/uv.lock"

            - name: Build Server
              working-directory: ./server
              run: uv run --no-dev excalibur build

            - name: Attest
              uses: actions/attest-build-provenance@v3
              if: ${{ !env.ACT && !github.event.repository.private }}
              with:
                  subject-path: "server/dist"

            - name: Upload Server Artifacts
              uses: actions/upload-artifact@v5
              with:
                  name: server
                  path: server/dist
                  if-no-files-found: error

    create-release:
        if: ${{ github.event_name != 'workflow_dispatch' }}
        name: Create Release
        runs-on: ubuntu-latest
        needs: [build-app-electron, build-app-pwa-mobile, build-server]
        permissions:
            contents: write
        steps:
            - uses: actions/checkout@v5

            - uses: actions/download-artifact@v5
              with:
                  path: artifacts

            - name: Prepare Release Notes
              id: prepare_release_notes
              run: |
                  # Read the full content of both changelogs
                  APP_CHANGELOG=$(cat app/changelog/${{ github.ref_name }}.md)
                  SERVER_CHANGELOG=$(cat server/changelog/${{ github.ref_name }}.md)

                  # Extract the header from the app changelog (first line) and change '##' to '#'
                  RELEASE_HEADER=$(echo "$APP_CHANGELOG" | head -n 1 | sed 's/^##/#/')

                  # Extract the content of the app changelog (from line 3 onwards to skip the header and blank line)
                  APP_BODY=$(echo "$APP_CHANGELOG" | tail -n +3)

                  # Extract the content of the server changelog (from line 3 onwards)
                  SERVER_BODY=$(echo "$SERVER_CHANGELOG" | tail -n +3)

                  # Combine everything into the final release body using the desired format
                  COMBINED_BODY=$(cat <<EOF
                  $RELEASE_HEADER

                  ## App

                  <details>
                  <summary>App Changelog</summary>

                  $APP_BODY
                  </details>

                  ## Server

                  <details>
                  <summary>Server Changelog</summary>

                  $SERVER_BODY
                  </details>
                  EOF
                  )

                  # Use a heredoc to safely pass the multiline string to the step output
                  echo "body<<EOF" >> $GITHUB_OUTPUT
                  echo "$COMBINED_BODY" >> $GITHUB_OUTPUT
                  echo "EOF" >> $GITHUB_OUTPUT

            - name: Create Draft Release
              uses: softprops/action-gh-release@v2
              if: ${{ github.token }}
              with:
                  body: ${{ steps.prepare_release_notes.outputs.body }}
                  files: |
                      artifacts/server/*
                      artifacts/app-pwa/*
                      artifacts/app-electron-*/*
                      artifacts/app-android/*
                  preserve_order: true
