name: Test

on:
    push:
        branches:
            - main
        paths:
            - app/**
            - server/**
    pull_request:
        branches:
            - main

jobs:
    test-app:
        name: Test App
        runs-on: ubuntu-latest
        if: ${{ !github.event.repository.private }}
        steps:
            - uses: actions/checkout@v6
              with:
                  sparse-checkout: app

            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                  version: 10

            - name: Set up Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "22"
                  cache: "pnpm"
                  cache-dependency-path: pnpm-lock.yaml

            - name: Install Dependencies
              working-directory: ./app
              run: pnpm install --filter !excalibur-electron

            - name: Run Unit Tests
              working-directory: ./app/packages/main
              run: pnpm run test:unit-run

            - name: Run Component Tests
              working-directory: ./app/packages/main
              run: pnpm run test:component

    test-server:
        name: Test Server
        runs-on: ubuntu-latest
        if: ${{ !github.event.repository.private }}
        steps:
            - uses: actions/checkout@v6
              with:
                  sparse-checkout: server

            - name: Set up Python
              uses: actions/setup-python@v6
              with:
                  python-version-file: "./server/pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@v7
              with:
                  enable-cache: true
                  version: "0.9.30"
                  cache-dependency-glob: "server/uv.lock"

            - name: Set Up Testing Environment
              working-directory: server
              run: |
                  uv run excalibur init -r
                  uv run excalibur user add --username test-user --password Password --vault-key g7uMn17DkmWI3PBtxmiCLnQf34nXuEfpgexHUNBMOW0\\=

            - name: Run Tests
              working-directory: server
              run: |
                  uv run --group test excalibur test
