name: Test End-to-End

on:
    pull_request:
        branches:
            - main
    workflow_dispatch:

jobs:
    test-e2e:
        name: Test End-to-End
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v5

            - name: Set up Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: "22"
                  cache: "npm"
                  cache-dependency-path: app/package-lock.json

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version-file: "./server/pyproject.toml"

            - name: Install uv
              uses: astral-sh/setup-uv@v6.5.0
              with:
                  enable-cache: true
                  version: "0.8.17"
                  cache-dependency-glob: "server/uv.lock"

            - name: Install App Dependencies
              working-directory: ./app
              run: npm ci

            - name: Install E2E Testing Dependencies
              working-directory: ./
              run: npm i

            - name: Run E2E Test
              working-directory: ./
              run: npm run test:e2e
